### Silver Layer - Data Cleaning & Feature Engineering

## Objective

The Silver layer transforms the raw Bronze datasets into a clean, standardized, and analysis-ready dataset.

This stage performs data cleaning, validation, preprocessing, and feature engineering. It also generates row-level KPIs that will be used later in the Gold Layer for Data Warehouse modeling, dashboards, and machine learning.

---

## Processing Steps

The Silver layer performs the following tasks:

### 1. Load Bronze Data
- Load the four raw datasets generated in the Bronze layer.
- Add a timeframe identifier.
- Merge all datasets into one unified dataset.

### 2. Data Cleaning
- Inspect the dataset.
- Convert timestamps into datetime format.
- Extract temporal attributes.
- Remove unnecessary columns.
- Handle missing values.
- Remove duplicate records.
- Validate numerical columns.

### 3. Feature Engineering
Generate analytical features including:

- Price KPIs
- Volume KPIs
- Trend Indicators
- Support & Resistance
- Breakout Signals
- Market Behavior Signals

### 4. Final Validation
- Remove rows affected by rolling calculations.
- Keep only analytical columns.
- Save the cleaned dataset.

---

## Output

**Input**

- bronze_15m.csv
- bronze_1h.csv
- bronze_4h.csv
- bronze_1d.csv

**Output**

- silver_bitcoin.csv

In [4]:
#import required libraries
import pandas as pd
import numpy as np

In [5]:
# Load Bronze datasets
df_15m = pd.read_csv(r"C:\Users\admin\Desktop\bronze layer\bronze_15m.csv")
df_1h  = pd.read_csv(r"C:\Users\admin\Desktop\bronze layer\bronze_1h.csv")
df_4h  = pd.read_csv(r"C:\Users\admin\Desktop\bronze layer\bronze_4h.csv")
df_1d  = pd.read_csv(r"C:\Users\admin\Desktop\bronze layer\bronze_1d.csv")

### Data Preprocessing

In [6]:
# Add timeframe labels
df_15m["timeframe"] = "15m"
df_1h["timeframe"] = "1h"
df_4h["timeframe"] = "4h"
df_1d["timeframe"] = "1d"

# Merge datasets
df = pd.concat(
    [df_15m, df_1h, df_4h, df_1d],
    ignore_index=True
)

In [ ]:
df.head()

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,timeframe
0,2018-01-01 00:00:00.000000,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000,1.675545e+06,1572,63.227133,8.576108e+05,0,15m
1,2018-01-01 00:15:00.000000,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000,1.321757e+06,1461,47.686389,6.422812e+05,0,15m
2,2018-01-01 00:30:00.000000,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000,1.078825e+06,1000,43.710406,5.900347e+05,0,15m
3,2018-01-01 00:45:00.000000,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000,1.917783e+06,1195,73.897993,1.000614e+06,0,15m
4,2018-01-01 01:00:00.000000,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000,9.778198e+05,898,34.257652,4.618369e+05,0,15m

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391510 entries, 0 to 391509
Data columns (total 13 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     391507 non-null  object
 1   Open                          391510 non-null  float64
 2   High                          391510 non-null  float64
 3   Low                           391510 non-null  float64
 4   Close                         391510 non-null  float64
 5   Volume                        391510 non-null  float64
 6   Close time                    391507 non-null  object
 7   Quote asset volume            391510 non-null  float64
 8   Number of trades              391510 non-null  int64
 9   Taker buy base asset volume   391510 non-null  float64
 10  Taker buy quote asset volume  391510 non-null  float64
 11  Ignore                        391510 non-null  int64
 12  timeframe                     391510 non-null  object
dtypes: float64(8), int64(2), object(3)
memory usage: 38.8+ MB

In [ ]:
df.describe()

,Open,High,Low,Close,Volume,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore
count,391510.000000,391510.000000,391510.000000,391510.000000,391510.000000,3.915100e+05,3.915100e+05,391510.000000,3.915100e+05,391510.0
mean,39325.245093,39432.640840,39213.157351,39325.886893,1969.506244,5.652247e+07,6.305209e+04,978.020394,2.791147e+07,0.0
std,32556.019527,32622.384136,32487.781864,32556.183340,9630.001303,2.517230e+08,2.731358e+05,4790.287864,1.248749e+08,0.0
min,3166.110000,3174.780000,3156.260000,3167.070000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.0
25%,9696.070000,9727.970000,9661.160000,9695.917500,220.137512,4.994165e+06,6.176000e+03,108.214681,2.384261e+06,0.0
50%,29320.140000,29373.595000,29268.725000,29320.400000,469.282420,1.402867e+07,1.555650e+04,232.889784,6.812442e+06,0.0
75%,62203.665000,62397.677500,62027.692500,62204.190000,1261.887156,3.800075e+07,4.372500e+04,629.808423,1.874148e+07,0.0
max,126011.180000,126199.630000,125648.010000,126011.180000,760705.362783,1.746531e+10,1.522359e+07,374775.574085,8.783916e+09,0.0

In [10]:
df.shape

(391510, 13)

In [ ]:
# Convert timestamps to datetime
df["Open time"] = pd.to_datetime(df["Open time"], format="mixed", utc=True)
df["Close time"] = pd.to_datetime(df["Close time"], format="mixed", utc=True)

# Sort records
df = df.sort_values("Open time").reset_index(drop=True)

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,Ignore,timeframe
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,0,15m
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,0,4h
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,0,1d
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,0,1h
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,0,15m
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,0,15m
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,0,15m
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,0,15m
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,0,1h
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,0,15m
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,0,15m
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,0,15m
12,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,0,1h
13,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,0,15m
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,0,15m
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,0,15m
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,0,15m
17,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,0,15m
18,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,0,1h
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,0,15m
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,0,15m
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,0,15m
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,0,1h
23,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,0,4h
24,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,0,15m
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,0,15m
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,0,15m
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,0,15m
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,0,15m
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,0,1h
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,0,15m
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,0,15m
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,0,15m
33,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,0,15m
34,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,0,1h
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,0,15m
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,0,15m
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,0,15m
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,0,1h
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,0,15m
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,0,15m
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,0,15m
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,0,15m
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,0,1h
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,0,4h
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,0,15m
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,0,15m
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,0,15m
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,0,15m
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,0,15m

In [ ]:
# Remove unnecessary column
df = df.drop(columns=["Ignore"])

In [ ]:
# Extract calendar attributes
df["year"] = df["Open time"].dt.year
df["month"] = df["Open time"].dt.month
df["day"] = df["Open time"].dt.day
df["quarter"] = df["Open time"].dt.quarter

In [ ]:
# Check missing values
df[["year","month","day","quarter"]].isna().sum()

year       3
month      3
day        3
quarter    3
dtype: int64

In [ ]:
# display the first five rows that contain at least one missing value (NaN) in any column
df[df.isna().any(axis=1)].head()

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
391507,NaT,66226.07,66269.52,66116.59,66269.52,100.41320,NaT,6.646592e+06,25639,66.32040,4.389696e+06,15m,NaN,NaN,NaN,NaN
391508,NaT,66368.15,66476.64,66076.56,66206.34,520.15584,NaT,3.446694e+07,160615,258.69663,1.714831e+07,1h,NaN,NaN,NaN,NaN
391509,NaT,67292.15,67292.15,66348.00,66614.35,3808.29082,NaT,2.547718e+08,642459,1581.91921,1.058234e+08,4h,NaN,NaN,NaN,NaN

In [ ]:
# Remove invalid timestamp rows
df = df.dropna(subset=["Open time"])
# Reset index
df = df.reset_index(drop=True)

In [ ]:
# Convert calendar fields to integer
df["year"] = df["Open time"].dt.year.astype(int)
df["month"] = df["Open time"].dt.month.astype(int)
df["day"] = df["Open time"].dt.day.astype(int)
df["quarter"] = df["Open time"].dt.quarter.astype(int)

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,15m,2018,1,1,1
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,4h,2018,1,1,1
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,1d,2018,1,1,1
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,1h,2018,1,1,1
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,15m,2018,1,1,1
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,15m,2018,1,1,1
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,15m,2018,1,1,1
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,15m,2018,1,1,1
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,1h,2018,1,1,1
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,15m,2018,1,1,1
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,15m,2018,1,1,1
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,15m,2018,1,1,1
12,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,1h,2018,1,1,1
13,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,15m,2018,1,1,1
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,15m,2018,1,1,1
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,15m,2018,1,1,1
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,15m,2018,1,1,1
17,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,15m,2018,1,1,1
18,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,1h,2018,1,1,1
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,15m,2018,1,1,1
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,15m,2018,1,1,1
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,15m,2018,1,1,1
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,1h,2018,1,1,1
23,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,4h,2018,1,1,1
24,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,15m,2018,1,1,1
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,15m,2018,1,1,1
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,15m,2018,1,1,1
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,15m,2018,1,1,1
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,15m,2018,1,1,1
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,1h,2018,1,1,1
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,15m,2018,1,1,1
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,15m,2018,1,1,1
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,15m,2018,1,1,1
33,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,15m,2018,1,1,1
34,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,1h,2018,1,1,1
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,15m,2018,1,1,1
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,15m,2018,1,1,1
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,15m,2018,1,1,1
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,1h,2018,1,1,1
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,15m,2018,1,1,1
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,15m,2018,1,1,1
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,15m,2018,1,1,1
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,15m,2018,1,1,1
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,1h,2018,1,1,1
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,4h,2018,1,1,1
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,15m,2018,1,1,1
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,15m,2018,1,1,1
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,15m,2018,1,1,1
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,15m,2018,1,1,1
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,15m,2018,1,1,1

In [ ]:
df.isna().sum()

Open time                       0
Open                            0
High                            0
Low                             0
Close                           0
Volume                          0
Close time                      0
Quote asset volume              0
Number of trades                0
Taker buy base asset volume     0
Taker buy quote asset volume    0
timeframe                       0
year                            0
month                           0
day                             0
quarter                         0
dtype: int64

In [ ]:
# Check duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
df.duplicated(subset=["Open time","timeframe"]).sum()

np.int64(6)

In [ ]:
df[df.duplicated(subset=["Open time","timeframe"], keep=False)]

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter
23343,2018-07-06 00:00:00+00:00,108700.00,109111.00,108518.83,108888.00,1086.391210,2018-07-06 03:59:59.999000+00:00,1.182862e+08,214025,508.738310,5.538955e+07,4h,2018,7,6,3
23344,2018-07-06 00:00:00+00:00,6529.20,6553.00,6511.00,6530.00,4120.321071,2018-07-06 03:59:59.999000+00:00,2.690673e+07,24305,2337.061505,1.526290e+07,4h,2018,7,6,3
23363,2018-07-06 04:00:00+00:00,6530.00,6533.63,6425.00,6478.85,5824.504486,2018-07-06 07:59:59.999000+00:00,3.778332e+07,37316,3043.078755,1.974576e+07,4h,2018,7,6,3
23364,2018-07-06 04:00:00+00:00,108888.00,108978.64,107505.00,107573.29,3616.089460,2018-07-06 07:59:59.999000+00:00,3.905847e+08,627971,1611.098070,1.740189e+08,4h,2018,7,6,3
23470,2018-07-07 00:00:00+00:00,6609.79,6613.99,6581.05,6596.93,766.671591,2018-07-07 00:59:59.999000+00:00,5.055038e+06,6145,417.287181,2.751863e+06,1h,2018,7,7,3
23472,2018-07-07 00:00:00+00:00,107469.22,107813.04,107440.63,107692.01,228.631950,2018-07-07 00:59:59.999000+00:00,2.461733e+07,42593,138.742240,1.493892e+07,1h,2018,7,7,3
23478,2018-07-07 01:00:00+00:00,107692.01,107941.99,107689.91,107911.20,255.841360,2018-07-07 01:59:59.999000+00:00,2.757870e+07,33521,129.597780,1.397040e+07,1h,2018,7,7,3
23479,2018-07-07 01:00:00+00:00,6596.93,6600.00,6561.01,6566.01,887.436249,2018-07-07 01:59:59.999000+00:00,5.837711e+06,6193,488.621779,3.214876e+06,1h,2018,7,7,3
23504,2018-07-07 06:00:00+00:00,6598.00,6600.00,6592.88,6592.90,184.610237,2018-07-07 06:14:59.999000+00:00,1.217864e+06,924,73.630565,4.857697e+05,15m,2018,7,7,3
23505,2018-07-07 06:00:00+00:00,108254.95,108254.96,108090.24,108115.55,64.056100,2018-07-07 06:14:59.999000+00:00,6.927307e+06,10111,21.874150,2.365207e+06,15m,2018,7,7,3
23507,2018-07-07 06:15:00+00:00,6592.90,6592.90,6572.01,6583.30,184.209006,2018-07-07 06:29:59.999000+00:00,1.212812e+06,1483,90.503658,5.958897e+05,15m,2018,7,7,3
23508,2018-07-07 06:15:00+00:00,108115.55,108130.80,108057.35,108104.01,41.816480,2018-07-07 06:29:59.999000+00:00,4.519670e+06,9175,21.072920,2.277494e+06,15m,2018,7,7,3

In [ ]:
# Keep the record with the highest number of trades for each duplicated
# Open time and timeframe, then sort the dataset df = df.sort_values("Number of trades", ascending=False)
df = df.drop_duplicates(subset=["Open time","timeframe"], keep="first")
df = df.sort_values("Open time")
df = df.reset_index(drop=True)

In [ ]:
df.dtypes

Open time                       datetime64[ns, UTC]
Open                                        float64
High                                        float64
Low                                         float64
Close                                       float64
Volume                                      float64
Close time                      datetime64[ns, UTC]
Quote asset volume                          float64
Number of trades                              int64
Taker buy base asset volume                 float64
Taker buy quote asset volume                float64
timeframe                                    object
year                                          int64
month                                         int64
day                                           int64
quarter                                       int64
dtype: object

In [ ]:
# Validate numeric columns
(df[["Open","High","Low","Close","Volume"]] < 0).sum()

Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

### Feature Engnineering

#### price

In [27]:
#price movement

df['price_change'] = df['Close'] - df['Open']


# Return
df['return_pct'] = df['price_change'] / df['Open']

# Volatility
df['volatility'] = df['High'] - df['Low']

In [ ]:
df.head(50)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,Taker buy quote asset volume,timeframe,year,month,day,quarter,price_change,return_pct,volatility
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,8.576108e+05,15m,2018,1,1,1,-159.50,-0.011629,315.64
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,9.937537e+06,4h,2018,1,1,1,-305.62,-0.022283,560.27
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,5.280975e+07,1d,2018,1,1,1,-335.65,-0.024472,1068.55
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,3.090541e+06,1h,2018,1,1,1,-186.64,-0.013608,315.64
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,6.422812e+05,15m,2018,1,1,1,-12.63,-0.000933,148.87
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,5.900347e+05,15m,2018,1,1,1,-29.59,-0.002192,95.37
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,1.000614e+06,15m,2018,1,1,1,34.36,0.002546,240.87
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,4.618369e+05,15m,2018,1,1,1,-83.36,-0.006162,169.46
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,2.430449e+06,1h,2018,1,1,1,-325.93,-0.024091,440.51
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,6.111437e+05,15m,2018,1,1,1,90.01,0.006682,150.26
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,5.219765e+05,15m,2018,1,1,1,-119.98,-0.008848,129.99
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,8.354925e+05,15m,2018,1,1,1,-236.95,-0.017630,284.63
12,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,5.424858e+05,15m,2018,1,1,1,184.00,0.013936,209.73
13,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,2.558505e+06,1h,2018,1,1,1,127.18,0.009633,218.43
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,5.726181e+05,15m,2018,1,1,1,-162.00,-0.012101,163.00
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,7.073543e+05,15m,2018,1,1,1,73.28,0.005531,149.99
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,7.360464e+05,15m,2018,1,1,1,-8.79,-0.000659,158.34
17,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,1.858041e+06,1h,2018,1,1,1,79.77,0.005984,321.27
18,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,4.747012e+05,15m,2018,1,1,1,114.73,0.008607,160.76
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,5.859573e+05,15m,2018,1,1,1,122.37,0.009105,171.27
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,4.433612e+05,15m,2018,1,1,1,-62.37,-0.004599,211.01
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,3.540215e+05,15m,2018,1,1,1,-99.97,-0.007400,109.96
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,2.328058e+06,1h,2018,1,1,1,166.03,0.012358,301.14
23,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,4.567588e+05,15m,2018,1,1,1,-83.27,-0.006198,160.92
24,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,7.998796e+06,4h,2018,1,1,1,135.37,0.010076,496.40
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,5.691023e+05,15m,2018,1,1,1,75.01,0.005617,126.34
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,6.153539e+05,15m,2018,1,1,1,77.42,0.005765,148.06
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,6.868429e+05,15m,2018,1,1,1,93.60,0.006930,157.88
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,6.803406e+05,15m,2018,1,1,1,11.94,0.000877,125.81
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,1.935710e+06,1h,2018,1,1,1,-56.21,-0.004128,172.50
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,6.259618e+05,15m,2018,1,1,1,18.51,0.001361,166.43
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,3.756632e+05,15m,2018,1,1,1,-38.50,-0.002827,99.00
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,2.537446e+05,15m,2018,1,1,1,0.04,0.000003,73.50
33,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,1.718753e+06,1h,2018,1,1,1,241.41,0.017831,290.00
34,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,2.833936e+05,15m,2018,1,1,1,-6.68,-0.000493,61.63
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,8.124585e+05,15m,2018,1,1,1,155.76,0.011510,190.62
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,2.814531e+05,15m,2018,1,1,1,34.71,0.002536,129.99
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,3.414476e+05,15m,2018,1,1,1,57.93,0.004222,97.90
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,5.858475e+05,15m,2018,1,1,1,-5.00,-0.000363,148.55
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,2.016275e+06,1h,2018,1,1,1,-209.65,-0.015214,263.53
40,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,5.707639e+05,15m,2018,1,1,1,-76.99,-0.005589,175.99
41,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,5.703255e+05,15m,2018,1,1,1,-53.05,-0.003873,185.00
42,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,2.893379e+05,15m,2018,1,1,1,-74.62,-0.005469,104.95
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,7.792109e+06,4h,2018,1,1,1,-349.42,-0.025749,734.11
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,1.664737e+06,1h,2018,1,1,1,-69.99,-0.005158,335.24
45,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,2.791373e+05,15m,2018,1,1,1,86.25,0.006356,145.00
46,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,4.767699e+05,15m,2018,1,1,1,-23.34,-0.001709,124.97
47,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,6.318254e+05,15m,2018,1,1,1,-179.62,-0.013193,249.96
48,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,2.770044e+05,15m,2018,1,1,1,84.99,0.006335,93.93
49,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,3.360020e+05,15m,2018,1,1,1,89.86,0.006656,140.87

#### trend

In [29]:
# Trend Direction
df['trend_direction'] = np.where(df['price_change'] > 0, 1, -1)

# Trend Streak
df['trend_streak'] = df.groupby('timeframe')['trend_direction'].transform(
    lambda x: (x != x.shift()).cumsum()
)

# Trend Length
df['trend_length'] = df.groupby(['timeframe', 'trend_streak']).cumcount() + 1

# Trend Strength
df['trend_strength'] = np.where(
    df['Close'] != 0,
    (df['price_change'] / df['Close']) * df['Volume'],
    0
)

In [30]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,Quote asset volume,Number of trades,Taker buy base asset volume,...,month,day,quarter,price_change,return_pct,volatility,trend_direction,trend_streak,trend_length,trend_strength
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,1,1,1,-159.50,-0.011629,315.64,-1,1,1,-1.454451
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,1,1,1,-305.62,-0.022283,560.27,-1,1,1,-38.201385
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,1,1,1,-335.65,-0.024472,1068.55,-1,1,1,-215.987911
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,1,1,1,-186.64,-0.013608,315.64,-1,1,1,-6.116338
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,1,1,1,-12.63,-0.000933,148.87,-1,1,2,-0.091669
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,1,1,1,-29.59,-0.002192,95.37,-1,1,3,-0.175523
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,1,1,1,34.36,0.002546,240.87,1,2,1,0.359879
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,1,1,1,-83.36,-0.006162,169.46,-1,3,1,-0.449717
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,1,1,1,-325.93,-0.024091,440.51,-1,1,2,-9.471923
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,1,1,1,90.01,0.006682,150.26,1,4,1,0.583218

#### volume & market activity

In [31]:
# Buy Volume
df = df.rename(columns={'Taker buy base asset volume': 'buy_volume'})

# Sell Volume
df['sell_volume'] = df['Volume'] - df['buy_volume']


# Buy Ratio
df['buy_ratio'] = np.where(
    df['Volume'] != 0,
    df['buy_volume'] / df['Volume'],
    0
)

# Sell Ratio
df['sell_ratio'] = np.where(
    df['Volume'] != 0,
    df['sell_volume'] / df['Volume'],
    0
)

# Net Order Flow
df['order_flow'] = df['buy_volume'] - df['sell_volume']

# Capital Flow
df.rename(columns={'Quote asset volume': 'capital_flow'}, inplace=True)
#trade activity
df.rename(columns={'Number of trades': 'trade_activity'}, inplace=True)

In [32]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,return_pct,volatility,trend_direction,trend_streak,trend_length,trend_strength,sell_volume,buy_ratio,sell_ratio,order_flow
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,-0.011629,315.64,-1,1,1,-1.454451,60.388880,0.511480,0.488520,2.838253
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,-0.022283,560.27,-1,1,1,-38.201385,936.686141,0.441186,0.558814,-197.167475
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,-0.024472,1068.55,-1,1,1,-215.987911,4647.976898,0.460160,0.539840,-686.037952
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,-0.013608,315.64,-1,1,1,-6.116338,214.834278,0.515436,0.484564,13.687643
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,-0.000933,148.87,-1,1,2,-0.091669,50.450041,0.485919,0.514081,-2.763652
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,-0.002192,95.37,-1,1,3,-0.175523,36.193631,0.547036,0.452964,7.516775
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,0.002546,240.87,1,2,1,0.359879,67.801726,0.521511,0.478489,6.096267
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,-0.006162,169.46,-1,3,1,-0.449717,38.279881,0.472275,0.527725,-4.022229
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,-0.024091,440.51,-1,1,2,-9.471923,202.856603,0.471310,0.528690,-22.016200
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,0.006682,150.26,1,4,1,0.583218,42.725801,0.513716,0.486284,2.410156

#### support & resistance

In [33]:
df['support'] = df['Close'] - df['Low']
df['resistance'] = df['High'] - df['Close']

In [34]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,trend_direction,trend_streak,trend_length,trend_strength,sell_volume,buy_ratio,sell_ratio,order_flow,support,resistance
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,-1,1,1,-1.454451,60.388880,0.511480,0.488520,2.838253,156.14,159.50
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,-1,1,1,-38.201385,936.686141,0.441186,0.558814,-197.167475,254.65,305.62
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,-1,1,1,-215.987911,4647.976898,0.460160,0.539840,-686.037952,630.00,438.55
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,-1,1,1,-6.116338,214.834278,0.515436,0.484564,13.687643,129.00,186.64
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,-1,1,2,-0.091669,50.450041,0.485919,0.514081,-2.763652,119.12,29.75
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,-1,1,3,-0.175523,36.193631,0.547036,0.452964,7.516775,20.41,74.96
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,1,2,1,0.359879,67.801726,0.521511,0.478489,6.096267,79.01,161.86
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,-1,3,1,-0.449717,38.279881,0.472275,0.527725,-4.022229,43.35,126.11
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,-1,1,2,-9.471923,202.856603,0.471310,0.528690,-22.016200,47.68,392.83
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,1,4,1,0.583218,42.725801,0.513716,0.486284,2.410156,114.37,35.89

In [35]:
df['avg_volume_20'] = df.groupby('timeframe')['Volume'].transform(
    lambda x: x.rolling(20).mean()
)

df['avg_volatility_20'] = df.groupby('timeframe')['volatility'].transform(
    lambda x: x.rolling(20).mean()
)

In [36]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,trend_length,trend_strength,sell_volume,buy_ratio,sell_ratio,order_flow,support,resistance,avg_volume_20,avg_volatility_20
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,1,-1.454451,60.388880,0.511480,0.488520,2.838253,156.14,159.50,NaN,NaN
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,1,-38.201385,936.686141,0.441186,0.558814,-197.167475,254.65,305.62,NaN,NaN
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,1,-215.987911,4647.976898,0.460160,0.539840,-686.037952,630.00,438.55,NaN,NaN
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,1,-6.116338,214.834278,0.515436,0.484564,13.687643,129.00,186.64,NaN,NaN
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,2,-0.091669,50.450041,0.485919,0.514081,-2.763652,119.12,29.75,NaN,NaN
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,3,-0.175523,36.193631,0.547036,0.452964,7.516775,20.41,74.96,NaN,NaN
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,1,0.359879,67.801726,0.521511,0.478489,6.096267,79.01,161.86,NaN,NaN
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,1,-0.449717,38.279881,0.472275,0.527725,-4.022229,43.35,126.11,NaN,NaN
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,2,-9.471923,202.856603,0.471310,0.528690,-22.016200,47.68,392.83,NaN,NaN
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,1,0.583218,42.725801,0.513716,0.486284,2.410156,114.37,35.89,NaN,NaN

In [37]:
#breakout up and down

df['rolling_high_20'] = df.groupby('timeframe')['High'].transform(
    lambda x: x.rolling(20).max().shift(1)
)
df['rolling_low_20'] = df.groupby('timeframe')['Low'].transform(
    lambda x: x.rolling(20).min().shift(1)
)

df['breakout_up'] = np.where(
    (df['Close'] > df['rolling_high_20']) &
    (df['Volume'] > df['avg_volume_20']),
    1, 0
)

df['breakout_down'] = np.where(
    (df['Close'] < df['rolling_low_20']) &
    (df['Volume'] > df['avg_volume_20']),
    1, 0
)

In [38]:

#market behavior

#high volatility
df['high_volatility'] = np.where(
    df['volatility'] > df['avg_volatility_20'],
    1, 0
)

#volatility streak
df['volatility_streak'] = df.groupby('timeframe')['high_volatility'].transform(
    lambda x: (x != x.shift()).cumsum()
)
#high volatility length
df['high_volatility_length'] = df.groupby(['timeframe', 'volatility_streak']).cumcount() + 1

#compression
df['compression'] = np.where(
    (df['volatility'] < df['avg_volatility_20'] * 0.5) &
    (df['Volume'] < df['avg_volume_20']),
    1, 0
)

In [39]:
#volume spike
df['volume_spike'] = np.where(
    (df['Volume'] > df['avg_volume_20'] * 1.5) &
    (df['return_pct'].abs() > 0.01),
    1, 0
)

#overheating
df['overheating'] = np.where(
    (df['buy_ratio'] > 0.6) &
    (df['Volume'] > df['avg_volume_20'] * 1.5) &
    (df['return_pct'] > 0),
    1, 0
)

In [40]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,rolling_high_20,rolling_low_20,breakout_up,breakout_down,high_volatility,volatility_streak,high_volatility_length,compression,volume_spike,overheating
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,NaN,NaN,0,0,0,1,1,0,0,0
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,NaN,NaN,0,0,0,1,1,0,0,0
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,NaN,NaN,0,0,0,1,1,0,0,0
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,NaN,NaN,0,0,0,1,1,0,0,0
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,NaN,NaN,0,0,0,1,2,0,0,0
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,NaN,NaN,0,0,0,1,3,0,0,0
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,NaN,NaN,0,0,0,1,4,0,0,0
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,NaN,NaN,0,0,0,1,5,0,0,0
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,NaN,NaN,0,0,0,1,2,0,0,0
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,NaN,NaN,0,0,0,1,6,0,0,0

In [ ]:
#whale activity
rows_per_year = {"15m": 35040, "1h": 8760, "4h": 2190, "1d": 365}

def stable_whale_threshold(group):
    tf = group.name
    window = rows_per_year.get(tf, 365)
    return group.rolling(window=window, min_periods=30).quantile(0.95)

df['whale_threshold'] = df.groupby('timeframe')['Volume'].transform(stable_whale_threshold)


df['avg_trade_activity_20'] = df.groupby('timeframe')['trade_activity'].transform(
    lambda x: x.rolling(20).mean()
)


df['whale_activity'] = np.where(
    (df['Volume'] > df['whale_threshold']) &
    (df['trade_activity'] < df['avg_trade_activity_20']),
    1, 0
)

In [42]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,breakout_down,high_volatility,volatility_streak,high_volatility_length,compression,volume_spike,overheating,whale_threshold,avg_trade_activity_20,whale_activity
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,0,0,1,1,0,0,0,NaN,NaN,0
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,0,0,1,1,0,0,0,NaN,NaN,0
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,0,0,1,1,0,0,0,NaN,NaN,0
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,0,0,1,1,0,0,0,NaN,NaN,0
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,0,0,1,2,0,0,0,NaN,NaN,0
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,0,0,1,3,0,0,0,NaN,NaN,0
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,0,0,1,4,0,0,0,NaN,NaN,0
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,0,0,1,5,0,0,0,NaN,NaN,0
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,0,0,1,2,0,0,0,NaN,NaN,0
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,0,0,1,6,0,0,0,NaN,NaN,0

In [ ]:
#check&load
df.isna().sum().sort_values(ascending=False)

whale_threshold                 116
rolling_high_20                  80
rolling_low_20                   80
avg_volatility_20                76
avg_trade_activity_20            76
avg_volume_20                    76
Close                             0
Volume                            0
Open time                         0
Open                              0
High                              0
Low                               0
timeframe                         0
Taker buy quote asset volume      0
buy_volume                        0
trade_activity                    0
capital_flow                      0
Close time                        0
year                              0
month                             0
trend_streak                      0
trend_length                      0
day                               0
quarter                           0
price_change                      0
return_pct                        0
volatility                        0
trend_direction                   0
support                           0
order_flow                        0
sell_ratio                        0
buy_ratio                         0
sell_volume                       0
trend_strength                    0
resistance                        0
breakout_up                       0
high_volatility                   0
breakout_down                     0
volatility_streak                 0
high_volatility_length            0
volume_spike                      0
compression                       0
overheating                       0
whale_activity                    0
dtype: int64

In [ ]:
df[df.isna().any(axis=1)].head(50)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,breakout_down,high_volatility,volatility_streak,high_volatility_length,compression,volume_spike,overheating,whale_threshold,avg_trade_activity_20,whale_activity
0,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13556.15,123.616013,2018-01-01 00:14:59.999000+00:00,1.675545e+06,1572,63.227133,...,0,0,1,1,0,0,0,NaN,NaN,0
1,2018-01-01 00:00:00+00:00,13715.65,13715.65,13155.38,13410.03,1676.204807,2018-01-01 03:59:59.999000+00:00,2.251607e+07,19438,739.518666,...,0,0,1,1,0,0,0,NaN,NaN,0
2,2018-01-01 00:00:00+00:00,13715.65,13818.55,12750.00,13380.00,8609.915844,2018-01-01 23:59:59.999000+00:00,1.147997e+08,105595,3961.938946,...,0,0,1,1,0,0,0,NaN,NaN,0
3,2018-01-01 00:00:00+00:00,13715.65,13715.65,13400.01,13529.01,443.356199,2018-01-01 00:59:59.999000+00:00,5.993910e+06,5228,228.521921,...,0,0,1,1,0,0,0,NaN,NaN,0
4,2018-01-01 00:15:00+00:00,13533.75,13550.87,13402.00,13521.12,98.136430,2018-01-01 00:29:59.999000+00:00,1.321757e+06,1461,47.686389,...,0,0,1,2,0,0,0,NaN,NaN,0
5,2018-01-01 00:30:00+00:00,13500.00,13545.37,13450.00,13470.41,79.904037,2018-01-01 00:44:59.999000+00:00,1.078825e+06,1000,43.710406,...,0,0,1,3,0,0,0,NaN,NaN,0
6,2018-01-01 00:45:00+00:00,13494.65,13690.87,13450.00,13529.01,141.699719,2018-01-01 00:59:59.999000+00:00,1.917783e+06,1195,73.897993,...,0,0,1,4,0,0,0,NaN,NaN,0
7,2018-01-01 01:00:00+00:00,13528.99,13571.74,13402.28,13445.63,72.537533,2018-01-01 01:14:59.999000+00:00,9.778198e+05,898,34.257652,...,0,0,1,5,0,0,0,NaN,NaN,0
8,2018-01-01 01:00:00+00:00,13528.99,13595.89,13155.38,13203.06,383.697006,2018-01-01 01:59:59.999000+00:00,5.154522e+06,4534,180.840403,...,0,0,1,2,0,0,0,NaN,NaN,0
9,2018-01-01 01:15:00+00:00,13469.99,13595.89,13445.63,13560.00,87.861758,2018-01-01 01:29:59.999000+00:00,1.189941e+06,939,45.135957,...,0,0,1,6,0,0,0,NaN,NaN,0
10,2018-01-01 01:30:00+00:00,13559.99,13559.99,13430.00,13440.01,74.368405,2018-01-01 01:44:59.999000+00:00,1.004038e+06,1047,38.653471,...,0,0,1,7,0,0,0,NaN,NaN,0
11,2018-01-01 01:45:00+00:00,13440.01,13440.01,13155.38,13203.06,148.929310,2018-01-01 01:59:59.999000+00:00,1.982724e+06,1650,62.793323,...,0,0,1,8,0,0,0,NaN,NaN,0
12,2018-01-01 02:00:00+00:00,13203.00,13411.76,13202.03,13387.00,108.542470,2018-01-01 02:14:59.999000+00:00,1.446924e+06,1528,40.703069,...,0,0,1,9,0,0,0,NaN,NaN,0
13,2018-01-01 02:00:00+00:00,13203.00,13418.43,13200.00,13330.18,429.064572,2018-01-01 02:59:59.999000+00:00,5.710192e+06,4887,192.237935,...,0,0,1,3,0,0,0,NaN,NaN,0
14,2018-01-01 02:15:00+00:00,13387.00,13388.00,13225.00,13225.00,95.186039,2018-01-01 02:29:59.999000+00:00,1.265431e+06,1079,43.068838,...,0,0,1,10,0,0,0,NaN,NaN,0
15,2018-01-01 02:30:00+00:00,13247.80,13349.99,13200.00,13321.08,111.719503,2018-01-01 02:44:59.999000+00:00,1.483295e+06,1074,53.247854,...,0,0,1,11,0,0,0,NaN,NaN,0
16,2018-01-01 02:45:00+00:00,13338.97,13418.43,13260.09,13330.18,113.616560,2018-01-01 02:59:59.999000+00:00,1.514541e+06,1206,55.218174,...,0,0,1,12,0,0,0,NaN,NaN,0
17,2018-01-01 03:00:00+00:00,13330.26,13611.27,13290.00,13410.03,420.087030,2018-01-01 03:59:59.999000+00:00,5.657448e+06,4789,137.918407,...,0,0,1,4,0,0,0,NaN,NaN,0
18,2018-01-01 03:00:00+00:00,13330.26,13450.76,13290.00,13444.99,89.019514,2018-01-01 03:14:59.999000+00:00,1.189070e+06,1070,35.514692,...,0,0,1,13,0,0,0,NaN,NaN,0
19,2018-01-01 03:15:00+00:00,13440.00,13611.27,13440.00,13562.37,112.273306,2018-01-01 03:29:59.999000+00:00,1.516663e+06,1415,43.355251,...,0,0,1,14,0,0,0,NaN,NaN,0
20,2018-01-01 03:30:00+00:00,13562.37,13611.01,13400.00,13500.00,105.619306,2018-01-01 03:44:59.999000+00:00,1.428926e+06,1051,32.728398,...,0,0,1,15,0,0,0,NaN,NaN,0
21,2018-01-01 03:45:00+00:00,13510.00,13510.00,13400.04,13410.03,113.174904,2018-01-01 03:59:59.999000+00:00,1.522789e+06,1253,26.320066,...,0,0,1,16,0,0,0,NaN,NaN,0
22,2018-01-01 04:00:00+00:00,13434.98,13623.29,13322.15,13601.01,340.807329,2018-01-01 04:59:59.999000+00:00,4.588047e+06,4563,172.957635,...,0,0,1,5,0,0,0,NaN,NaN,0
23,2018-01-01 04:00:00+00:00,13434.98,13483.07,13322.15,13351.71,94.759633,2018-01-01 04:14:59.999000+00:00,1.271041e+06,1255,34.071009,...,0,0,1,17,0,0,0,NaN,NaN,0
24,2018-01-01 04:00:00+00:00,13434.98,13818.55,13322.15,13570.35,1302.214836,2018-01-01 07:59:59.999000+00:00,1.770254e+07,18061,588.516222,...,0,0,1,2,0,0,0,NaN,NaN,0
25,2018-01-01 04:15:00+00:00,13354.99,13449.89,13323.55,13430.00,70.563137,2018-01-01 04:29:59.999000+00:00,9.432340e+05,1022,42.572089,...,0,0,1,18,0,0,0,NaN,NaN,0
26,2018-01-01 04:30:00+00:00,13429.99,13550.00,13401.94,13507.41,68.943608,2018-01-01 04:44:59.999000+00:00,9.290333e+05,1006,45.665955,...,0,0,1,19,0,0,0,NaN,NaN,0
27,2018-01-01 04:45:00+00:00,13507.41,13623.29,13465.41,13601.01,106.540951,2018-01-01 04:59:59.999000+00:00,1.444739e+06,1280,50.648582,...,0,0,1,20,0,0,0,NaN,1200.05,0
28,2018-01-01 05:00:00+00:00,13615.20,13677.83,13552.02,13627.14,185.935937,2018-01-01 05:14:59.999000+00:00,2.534197e+06,2119,49.916113,...,0,0,1,21,0,0,0,NaN,1227.40,0
29,2018-01-01 05:00:00+00:00,13615.20,13699.00,13526.50,13558.99,404.229046,2018-01-01 05:59:59.999000+00:00,5.499055e+06,5086,142.331058,...,0,0,1,6,0,0,0,NaN,NaN,0
30,2018-01-01 05:15:00+00:00,13600.00,13699.00,13532.57,13618.51,103.502867,2018-01-01 05:29:59.999000+00:00,1.408949e+06,1213,45.980964,...,0,1,2,1,0,0,0,NaN,1215.00,0
31,2018-01-01 05:30:00+00:00,13618.51,13629.00,13530.00,13580.01,70.523393,2018-01-01 05:44:59.999000+00:00,9.562368e+05,925,27.705653,...,0,0,3,1,0,0,0,NaN,1211.25,0
32,2018-01-01 05:45:00+00:00,13558.95,13600.00,13526.50,13558.99,44.266849,2018-01-01 05:59:59.999000+00:00,5.996720e+05,829,18.728328,...,0,0,3,2,1,0,0,NaN,1192.95,0
33,2018-01-01 06:00:00+00:00,13539.00,13800.00,13510.00,13780.41,264.989684,2018-01-01 06:59:59.999000+00:00,3.613408e+06,4072,126.077500,...,0,0,1,7,0,0,0,NaN,NaN,0
34,2018-01-01 06:00:00+00:00,13539.00,13571.63,13510.00,13532.32,58.377845,2018-01-01 06:14:59.999000+00:00,7.899298e+05,863,20.938556,...,0,0,3,3,1,0,0,NaN,1191.20,0
35,2018-01-01 06:15:00+00:00,13532.00,13701.13,13510.51,13687.76,99.588918,2018-01-01 06:29:59.999000+00:00,1.355583e+06,1275,59.744662,...,0,1,4,1,0,0,0,NaN,1208.00,0
36,2018-01-01 06:30:00+00:00,13687.76,13750.00,13620.01,13722.47,52.257108,2018-01-01 06:44:59.999000+00:00,7.143783e+05,997,20.579891,...,0,0,5,1,0,0,0,NaN,1205.50,0
37,2018-01-01 06:45:00+00:00,13722.48,13800.00,13702.10,13780.41,54.765813,2018-01-01 06:59:59.999000+00:00,7.535164e+05,937,24.814391,...,0,0,5,2,0,0,0,NaN,1169.85,0
38,2018-01-01 07:00:00+00:00,13780.00,13818.55,13670.00,13775.00,84.038319,2018-01-01 07:14:59.999000+00:00,1.157374e+06,1319,42.535515,...,0,1,6,1,0,0,0,NaN,1159.40,0
39,2018-01-01 07:00:00+00:00,13780.00,13818.55,13555.02,13570.35,292.188777,2018-01-01 07:59:59.999000+00:00,4.002026e+06,4340,147.150029,...,0,0,1,8,0,0,0,NaN,NaN,0
43,2018-01-01 08:00:00+00:00,13569.98,13735.24,13001.13,13220.56,1319.755931,2018-01-01 11:59:59.999000+00:00,1.765121e+07,17200,582.668293,...,0,0,1,3,0,0,0,NaN,NaN,0
44,2018-01-01 08:00:00+00:00,13569.98,13735.24,13400.00,13499.99,271.813553,2018-01-01 08:59:59.999000+00:00,3.681944e+06,3733,122.809696,...,0,0,1,9,0,0,0,NaN,NaN,0
50,2018-01-01 09:00:00+00:00,13499.97,13670.00,13459.11,13616.99,213.095829,2018-01-01 09:59:59.999000+00:00,2.893105e+06,3128,96.470199,...,0,0,1,10,0,0,0,NaN,NaN,0
54,2018-01-01 10:00:00+00:00,13632.00,13657.92,13497.98,13570.01,169.512196,2018-01-01 10:59:59.999000+00:00,2.298369e+06,2769,68.490957,...,0,0,1,11,0,0,0,NaN,NaN,0
60,2018-01-01 11:00:00+00:00,13573.00,13589.89,13001.13,13220.56,665.334353,2018-01-01 11:59:59.999000+00:00,8.777790e+06,7570,294.897441,...,0,0,1,12,0,0,0,NaN,NaN,0
64,2018-01-01 12:00:00+00:00,13220.56,13330.00,12750.00,13247.00,1831.933153,2018-01-01 15:59:59.999000+00:00,2.391259e+07,21357,830.314747,...,0,0,1,4,0,0,0,NaN,NaN,0
66,2018-01-01 12:00:00+00:00,13220.56,13300.00,13056.23,13172.42,260.492708,2018-01-01 12:59:59.999000+00:00,3.437453e+06,3618,115.163640,...,0,0,1,13,0,0,0,NaN,NaN,0
71,2018-01-01 13:00:00+00:00,13150.05,13200.41,12815.70,13017.00,451.901126,2018-01-01 13:59:59.999000+00:00,5.869105e+06,5719,248.601776,...,0,0,1,14,0,0,0,NaN,NaN,0
75,2018-01-01 14:00:00+00:00,12999.71,13245.00,12750.00,13211.39,692.467362,2018-01-01 14:59:59.999000+00:00,8.951403e+06,7132,299.429608,...,0,0,1,15,0,0,0,NaN,NaN,0
81,2018-01-01 15:00:00+00:00,13211.39,13330.00,13120.38,13247.00,427.071957,2018-01-01 15:59:59.999000+00:00,5.654630e+06,4888,167.119723,...,0,0,1,16,0,0,0,NaN,NaN,0

In [45]:

rolling_cols = ['avg_volume_20', 'avg_volatility_20', 'rolling_high_20', 'rolling_low_20', 'avg_trade_activity_20', 'whale_threshold']
df = df.dropna(subset=rolling_cols).reset_index(drop=True)

In [ ]:
df.head(10)

,Open time,Open,High,Low,Close,Volume,Close time,capital_flow,trade_activity,buy_volume,...,breakout_down,high_volatility,volatility_streak,high_volatility_length,compression,volume_spike,overheating,whale_threshold,avg_trade_activity_20,whale_activity
0,2018-01-01 07:15:00+00:00,13774.99,13775.99,13600.00,13698.00,74.453320,2018-01-01 07:29:59.999000+00:00,1.019043e+06,1312,41.686674,...,0,1,6,2,0,0,0,145.675994,1171.05,0
1,2018-01-01 07:30:00+00:00,13698.00,13775.00,13590.00,13644.95,89.776654,2018-01-01 07:44:59.999000+00:00,1.228408e+06,895,41.665985,...,0,1,6,3,0,0,0,145.314514,1162.10,0
2,2018-01-01 07:45:00+00:00,13644.97,13659.97,13555.02,13570.35,43.920484,2018-01-01 07:59:59.999000+00:00,5.972011e+05,814,21.261855,...,0,0,7,1,0,0,0,144.953035,1142.50,0
3,2018-01-01 08:00:00+00:00,13569.98,13665.00,13520.00,13656.23,58.542067,2018-01-01 08:14:59.999000+00:00,7.948098e+05,919,20.562018,...,0,1,8,1,0,0,0,144.591555,1134.95,0
4,2018-01-01 08:15:00+00:00,13656.23,13735.24,13610.27,13632.89,58.900513,2018-01-01 08:29:59.999000+00:00,8.054309e+05,869,34.862743,...,0,0,9,1,0,0,0,144.230076,1107.65,0
5,2018-01-01 08:30:00+00:00,13614.33,13649.96,13400.00,13434.71,104.766871,2018-01-01 08:44:59.999000+00:00,1.413295e+06,1204,46.829395,...,0,1,10,1,0,0,0,143.868596,1115.30,0
6,2018-01-01 08:45:00+00:00,13415.00,13508.69,13414.76,13499.99,49.604102,2018-01-01 08:59:59.999000+00:00,6.684083e+05,741,20.555540,...,0,0,11,1,0,0,0,143.507117,1089.70,0
7,2018-01-01 09:00:00+00:00,13499.97,13599.98,13459.11,13589.83,55.827255,2018-01-01 09:14:59.999000+00:00,7.554221e+05,825,24.819559,...,0,1,12,1,0,0,0,143.145637,1068.20,0
8,2018-01-01 09:15:00+00:00,13556.88,13650.00,13531.19,13549.77,55.580387,2018-01-01 09:29:59.999000+00:00,7.552835e+05,826,27.737784,...,0,0,13,1,0,0,0,142.784158,1058.40,0
9,2018-01-01 09:30:00+00:00,13531.82,13610.00,13510.01,13599.99,50.137197,2018-01-01 09:44:59.999000+00:00,6.803677e+05,696,20.799501,...,0,0,13,2,0,0,0,142.422678,1042.90,0

In [ ]:
df.isna().sum().sort_values(ascending=False)

Open time                       0
Open                            0
High                            0
Low                             0
Close                           0
Volume                          0
Close time                      0
capital_flow                    0
trade_activity                  0
buy_volume                      0
Taker buy quote asset volume    0
timeframe                       0
year                            0
month                           0
day                             0
quarter                         0
price_change                    0
return_pct                      0
volatility                      0
trend_direction                 0
trend_streak                    0
trend_length                    0
trend_strength                  0
sell_volume                     0
buy_ratio                       0
sell_ratio                      0
order_flow                      0
support                         0
resistance                      0
avg_volume_20                   0
avg_volatility_20               0
rolling_high_20                 0
rolling_low_20                  0
breakout_up                     0
breakout_down                   0
high_volatility                 0
volatility_streak               0
high_volatility_length          0
compression                     0
volume_spike                    0
overheating                     0
whale_threshold                 0
avg_trade_activity_20           0
whale_activity                  0
dtype: int64

In [ ]:
# Review dataset

df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391385 entries, 0 to 391384
Data columns (total 44 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     391385 non-null  datetime64[ns, UTC]
 1   Open                          391385 non-null  float64
 2   High                          391385 non-null  float64
 3   Low                           391385 non-null  float64
 4   Close                         391385 non-null  float64
 5   Volume                        391385 non-null  float64
 6   Close time                    391385 non-null  datetime64[ns, UTC]
 7   capital_flow                  391385 non-null  float64
 8   trade_activity                391385 non-null  int64
 9   buy_volume                    391385 non-null  float64
 10  Taker buy quote asset volume  391385 non-null  float64
 11  timeframe                     391385 non-null  object
 12  year                          391385 non-null  int64
 13  month                         391385 non-null  int64
 14  day                           391385 non-null  int64
 15  quarter                       391385 non-null  int64
 16  price_change                  391385 non-null  float64
 17  return_pct                    391385 non-null  float64
 18  volatility                    391385 non-null  float64
 19  trend_direction               391385 non-null  int64
 20  trend_streak                  391385 non-null  int64
 21  trend_length                  391385 non-null  int64
 22  trend_strength                391385 non-null  float64
 23  sell_volume                   391385 non-null  float64
 24  buy_ratio                     391385 non-null  float64
 25  sell_ratio                    391385 non-null  float64
 26  order_flow                    391385 non-null  float64
 27  support                       391385 non-null  float64
 28  resistance                    391385 non-null  float64
 29  avg_volume_20                 391385 non-null  float64
 30  avg_volatility_20             391385 non-null  float64
 31  rolling_high_20               391385 non-null  float64
 32  rolling_low_20                391385 non-null  float64
 33  breakout_up                   391385 non-null  int64
 34  breakout_down                 391385 non-null  int64
 35  high_volatility               391385 non-null  int64
 36  volatility_streak             391385 non-null  int64
 37  high_volatility_length        391385 non-null  int64
 38  compression                   391385 non-null  int64
 39  volume_spike                  391385 non-null  int64
 40  overheating                   391385 non-null  int64
 41  whale_threshold               391385 non-null  float64
 42  avg_trade_activity_20         391385 non-null  float64
 43  whale_activity                391385 non-null  int64
dtypes: datetime64[ns, UTC](2), float64(24), int64(17), object(1)
memory usage: 131.4+ MB

,Open,High,Low,Close,Volume,capital_flow,trade_activity,buy_volume,Taker buy quote asset volume,year,...,breakout_down,high_volatility,volatility_streak,high_volatility_length,compression,volume_spike,overheating,whale_threshold,avg_trade_activity_20,whale_activity
count,391385.000000,391385.000000,391385.000000,391385.000000,391385.000000,3.913850e+05,3.913850e+05,391385.000000,3.913850e+05,391385.000000,...,391385.000000,391385.000000,391385.000000,391385.000000,391385.000000,391385.000000,391385.000000,391385.000000,3.913850e+05,391385.000000
mean,39333.158370,39440.500293,39221.160604,39333.803455,1967.862692,5.651153e+07,6.305021e+04,977.185761,2.790568e+07,2021.748112,...,0.035045,0.378321,42936.805095,3.391635,0.097791,0.024081,0.014822,5287.096609,6.296430e+04,0.009584
std,32557.861859,32624.286368,32489.537836,32558.025841,9628.280507,2.517477e+08,2.731712e+05,4789.443879,1.248870e+08,2.447237,...,0.183893,0.484969,32185.565297,3.278856,0.297032,0.153301,0.120839,18195.690344,2.526503e+05,0.097427
min,3166.110000,3174.780000,3156.260000,3167.070000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,2018.000000,...,0.000000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,138.987163,3.489000e+02,0.000000
25%,9694.630000,9726.740000,9660.740000,9694.650000,220.138490,4.994906e+06,6.178000e+03,108.218680,2.384668e+06,2020.000000,...,0.000000,0.000000,14161.000000,1.000000,0.000000,0.000000,0.000000,1032.969019,6.973550e+03,0.000000
50%,29325.900000,29379.830000,29276.880000,29326.690000,469.253358,1.402873e+07,1.555700e+04,232.868270,6.812510e+06,2022.000000,...,0.000000,0.000000,36057.000000,2.000000,0.000000,0.000000,0.000000,1888.972847,1.701705e+04,0.000000
75%,62212.790000,62405.300000,62037.800000,62213.840000,1261.560966,3.799360e+07,4.372500e+04,629.555299,1.873743e+07,2024.000000,...,0.000000,1.000000,71219.000000,4.000000,0.000000,0.000000,0.000000,4468.379683,4.658350e+04,0.000000
max,126011.180000,126199.630000,125648.010000,126011.180000,760705.362783,1.746531e+10,1.522359e+07,374775.574085,8.783916e+09,2026.000000,...,1.000000,1.000000,105317.000000,34.000000,1.000000,1.000000,1.000000,437774.382210,9.914953e+06,1.000000

In [49]:
cols_to_keep = [

# Time
'Open time','timeframe',
'year','quarter','month','day',

# Price data
'Open','High','Low','Close',
'price_change','return_pct','volatility',

# Volume & market activity
'Volume','capital_flow','trade_activity',
'buy_volume','sell_volume',
'buy_ratio','sell_ratio','order_flow',

# Trend KPIs
'trend_direction','trend_length','trend_strength',

 'avg_volume_20',
 'avg_volatility_20',

# Market behavior signals
'volume_spike',
'high_volatility',
'high_volatility_length',
'compression',
'overheating',
'whale_activity',

# Breakouts
'breakout_up',
'breakout_down',

# Support & resistance
'support',
'resistance'
]

In [ ]:
# Review dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391385 entries, 0 to 391384
Data columns (total 44 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Open time                     391385 non-null  datetime64[ns, UTC]
 1   Open                          391385 non-null  float64
 2   High                          391385 non-null  float64
 3   Low                           391385 non-null  float64
 4   Close                         391385 non-null  float64
 5   Volume                        391385 non-null  float64
 6   Close time                    391385 non-null  datetime64[ns, UTC]
 7   capital_flow                  391385 non-null  float64
 8   trade_activity                391385 non-null  int64
 9   buy_volume                    391385 non-null  float64
 10  Taker buy quote asset volume  391385 non-null  float64
 11  timeframe                     391385 non-null  object
 12  year                          391385 non-null  int64
 13  month                         391385 non-null  int64
 14  day                           391385 non-null  int64
 15  quarter                       391385 non-null  int64
 16  price_change                  391385 non-null  float64
 17  return_pct                    391385 non-null  float64
 18  volatility                    391385 non-null  float64
 19  trend_direction               391385 non-null  int64
 20  trend_streak                  391385 non-null  int64
 21  trend_length                  391385 non-null  int64
 22  trend_strength                391385 non-null  float64
 23  sell_volume                   391385 non-null  float64
 24  buy_ratio                     391385 non-null  float64
 25  sell_ratio                    391385 non-null  float64
 26  order_flow                    391385 non-null  float64
 27  support                       391385 non-null  float64
 28  resistance                    391385 non-null  float64
 29  avg_volume_20                 391385 non-null  float64
 30  avg_volatility_20             391385 non-null  float64
 31  rolling_high_20               391385 non-null  float64
 32  rolling_low_20                391385 non-null  float64
 33  breakout_up                   391385 non-null  int64
 34  breakout_down                 391385 non-null  int64
 35  high_volatility               391385 non-null  int64
 36  volatility_streak             391385 non-null  int64
 37  high_volatility_length        391385 non-null  int64
 38  compression                   391385 non-null  int64
 39  volume_spike                  391385 non-null  int64
 40  overheating                   391385 non-null  int64
 41  whale_threshold               391385 non-null  float64
 42  avg_trade_activity_20         391385 non-null  float64
 43  whale_activity                391385 non-null  int64
dtypes: datetime64[ns, UTC](2), float64(24), int64(17), object(1)
memory usage: 131.4+ MB

In [52]:
df_final = df[cols_to_keep]
df_final.to_csv(r"C:\Users\admin\Desktop\silver_bitcoin.csv", index=False)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 391385 entries, 0 to 391384
Data columns (total 36 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Open time               391385 non-null  datetime64[ns, UTC]
 1   timeframe               391385 non-null  object
 2   year                    391385 non-null  int64
 3   quarter                 391385 non-null  int64
 4   month                   391385 non-null  int64
 5   day                     391385 non-null  int64
 6   Open                    391385 non-null  float64
 7   High                    391385 non-null  float64
 8   Low                     391385 non-null  float64
 9   Close                   391385 non-null  float64
 10  price_change            391385 non-null  float64
 11  return_pct              391385 non-null  float64
 12  volatility              391385 non-null  float64
 13  Volume                  391385 non-null  float64
 14  capital_flow            391385 non-null  float64
 15  trade_activity          391385 non-null  int64
 16  buy_volume              391385 non-null  float64
 17  sell_volume             391385 non-null  float64
 18  buy_ratio               391385 non-null  float64
 19  sell_ratio              391385 non-null  float64
 20  order_flow              391385 non-null  float64
 21  trend_direction         391385 non-null  int64
 22  trend_length            391385 non-null  int64
 23  trend_strength          391385 non-null  float64
 24  avg_volume_20           391385 non-null  float64
 25  avg_volatility_20       391385 non-null  float64
 26  volume_spike            391385 non-null  int64
 27  high_volatility         391385 non-null  int64
 28  high_volatility_length  391385 non-null  int64
 29  compression             391385 non-null  int64
 30  overheating             391385 non-null  int64
 31  whale_activity          391385 non-null  int64
 32  breakout_up             391385 non-null  int64
 33  breakout_down           391385 non-null  int64
 34  support                 391385 non-null  float64
 35  resistance              391385 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(19), int64(15), object(1)
memory usage: 107.5+ MB